version: '2'
services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sigdiv_net
  app:
    build: .
    container_name: ruby
    command: bundle exec puma -C config/puma.rb
    env_file: .env
    ports:
      - 3000:3000
    volumes:
      - .:/home/marviorocha/sigdiv
      - bundle_cache:/usr/local/bundle
    depends_on:
      - db
    networks:
      - sigdiv_net
  redis:
    container_name: redis
    image: redis:6.0.9-alpine
    networks:
      - sigdiv_net
  pgadmin:
    container_name: pagadmin
    image: dpage/pgadmin4:latest
    ports: 
      - 5050:80
    networks: 
      - sigdiv_net
volumes:
  postgres_data: {}
  bundle_cache:

networks:
  sigdiv_net:
    ipam:
        driver: default
        config:
            - subnet: 100.10.238.0/24
              gateway: 100.10.238.1