version: '3'
networks:
    RUBY:
services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - RUBY
  app:
    build: .
    container_name: ruby
    command: "bundle exec puma -p 9001 -e production"
    environment:
      - RAILS_ENV=production
    env_file: .env
    expose:
      - 9001
    volumes:
      - webdata:/home/marviorocha/sigdiv
    depends_on:
      - db
    networks:
      - RUBY
  web:
    image: infoslack/nginx-puma
    volumes:
      - webdata:/home/web/sigdiv
    ports:
      - 80:80
    depends_on:
      - app      
    networks:
      - RUBY
volumes:
  postgres_data: {}
  webdata:
