name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports: ['6379:6379']
        options: --entrypoint redis-server

    steps:
      - uses: actions/checkout@v1
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x
      # - name: Build and run tests
      #   env:
      #     DATABASE_URL: postgres://postgres:@localhost:5432/test
      #     REDIS_URL: redis://localhost:6379/0
      #     RAILS_ENV: sigdiv_test
      #     PGHOST: <%= ENV['POSTGRES_HOST'] %>
      #     PGUSER: <%= ENV['POSTGRES_USER'] %>
      #     PGPASSWORD: <%= ENV['POSTGRES_PASSWORD'] %>
      #     RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      #   run: |
      #     sudo apt-get -yqq install libpq-dev
      #     gem install bundler
      #     bundle install --jobs 4 --retry 3
      #     bundle exec rails db:prepare
      #     bundle exec rails test
      # - name: Run security checks
      #   run: |
      #     bin/bundler-audit --update
      #     bin/brakeman -q -w2
      # - name: Setup test database
  
      #   run: |
      #     bin/rails db:setup

      # - name: Run tests
      #   run: bin/rspec