name: Ruby-version
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_HOST: <%= ENV['POSTGRES_HOST'] %>
          POSTGRES_USER: <%= ENV['POSTGRES_USER'] %>
          POSTGRES_PASSWORD: <%= ENV['POSTGRES_PASSWORD'] %>
          POSTGRES_DB: sigdiv_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      redis:
        image: redis
        ports: ['6379:6379']
        options: --entrypoint redis-server

    steps:
      - uses: actions/checkout@v1
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x
      - name: Build and run tests
       environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: sigdiv_test
          POSTGRES_PASSWORD: admin123
       environment:
          BUNDLE_JOBS: "3"
          BUNDLE_RETRY: "3"
          PGHOST: 127.0.0.1
          PGUSER: postgres
          PGPASSWORD: admin123
          RAILS_ENV: test
        steps:
          - checkout
          - ruby/install-deps
          - node/install-packages:
              pkg-manager: yarn
              cache-key: "yarn.lock"
          - run:
              name: Wait for DB
              command: dockerize -wait tcp://localhost:5432 -timeout 1m
          - run:
              name: Database setup
              command: bundle exec rails db:schema:load --trace
          REDIS_URL: redis://localhost:6379/0
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rails db:prepare
          bundle exec rails test
      - name: Run security checks
        run: |
          bin/bundler-audit --update
          bin/brakeman -q -w2
  

      # - name: Run tests
      #   run: bin/rspec