name: Ruby-version
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_HOST: <%= ENV['POSTGRES_HOST'] %>
          POSTGRES_USER: <%= ENV['POSTGRES_USER'] %>
          POSTGRES_PASSWORD: <%= ENV['POSTGRES_PASSWORD'] %>
          POSTGRES_DB: sigdiv_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      redis:
        image: redis
        ports: ['6379:6379']
        options: --entrypoint redis-server

    steps:
      - uses: actions/checkout@v1
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x
      - name: Build and run tests
      - name: Cache Ruby Gems
          uses: actions/cache@v2
          with:
            path: vendor/bundle
            key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
            restore-keys: |
              ${{ runner.os }}-gems-      
      - name: Bundle Install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Run Tests
            env:
              PG_DATABASE: postgres
              PG_HOST: <%= ENV['POSTGRES_HOST'] %>
              PG_USER: <%= ENV['POSTGRES_USER'] %>
              PG_PASSWORD: <%= ENV['POSTGRES_PASSWORD'] %>
              RAILS_ENV: test
              WITH_COVERAGE: true
              DISABLE_SPRING: 1
            run: |
              bin/rails db:setup
              bundle exec rake test

        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rails db:prepare
          bundle exec rails test
      - name: Run security checks
        run: |
          bin/bundler-audit --update
          bin/brakeman -q -w2
  

      # - name: Run tests
      #   run: bin/rspec