name: CI
on: [push, pull_request]

jobs:
  run:
    name: Ruby
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-18.04, ubuntu-20.04]
        version: [2.7.x]
        exclude:
          - operating-system: ubuntu-18.04
            version: 2.4
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: use-ruby ${{ matrix.version }}
      uses: ./
      with:
        ruby-version: ${{ matrix.version}}
    - name: ruby version
      run: ruby -v