name: RSpec CI
on:
  push:
    branches:
      - 'developer'
      - 'production'
      - 'master'
  pull_request:
    branches:
      - '*'
jobs:
  test:
    name: 'Ruby: ${{ matrix.ruby }}, Rails: ${{ matrix.env.RAILS_VERSION }}'
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
       include:
         # Rails 6.0 builds >= 2.5.0
         - ruby: 3.0.0-preview2
           env:
             RAILS_VERSION: '~> 6.0.0'
         - ruby: 2.7
           env:
             RAILS_VERSION: '~> 6.0.0'
         - ruby: 2.6
           env:
             RAILS_VERSION: '~> 6.0.0'
         - ruby: 2.5
           env:
             RAILS_VERSION: '~> 6.0.0'
         # Rails 5.2 builds >= 2.2.2
         - ruby: 2.6.6
           env:
             RAILS_VERSION: '~> 5.2.0'
         - ruby: 2.5.8
           env:
             RAILS_VERSION: '~> 5.2.0'
         - ruby: 2.4.10
           env:
             RAILS_VERSION: '~> 5.2.0'
         - ruby: 2.3.8
           env:
             RAILS_VERSION: '~> 5.2.0'
    env: ${{ matrix.env }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: bundle install --binstubs
      - run: bin/rspec
        continue-on-error: ${{ matrix.allow_failure || false }}